#数据库连接池
spring:
  fakerdatadb:
    datasource:
      username: ENC(sICuXLxiL16DpjVuXRC1b7Bp7A0UE4l9)
      password: ENC(5JdunLJMWdpjJxh6fYmWvXxgf38SjcNIsL+9hJ/MlcU=)
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.103.220.45:3306/fakerdata?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=UTC
  akiskydb:
    datasource:
      username: ENC(fcVVrlODmxDdDMGPEZoJvg==)
      password: ENC(nk7lU2rIWDxOIYHab/7L2i6pknl+l9fT)
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.103.220.45:3306/akisky?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=UTC
  twitterdatadb:
    datasource:
      username: ENC(2utPJty4yNtPWriXg+WJNmxLI573k3gK)
      password: ENC(iQPuaIDwqSmptaN8Uj600zt1c5MWcuBylWDJUODsXQQ=)
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.103.220.45:3306/twitterdata?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=UTC
  data:
    mongodb:
      host: 47.103.220.45
      port: 27017
      database: cyber
      username: cyberwanderer
      password: ENC(QJHOprkX5lTgvhO2heGM5a534rVaphVq)
#mybatis xml位置
mybatis:
  mapper-locations: classpath:mapper/*.xml


