#数据库连接池
spring:
  datasource:
    username: fakerData
    password: N48HN4sD2HPGfkfp
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.220.45:3306/fakerdata?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=UTC
#jdbc:mysql://47.103.220.45:3306/akisky?useUnicode=true&amp;charaterEncoding=UTF-8&amp;serverTimezone=UTC
#AkiSky
#GMGGPOKSIRUDE
#mybatis xml位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

